[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Surrogate-Control = "no-store"
